- name: template /etc/sysconfig/transparent_hugepages
  template: src=transparent_hugepages.j2 dest=/etc/sysconfig/transparent_hugepages mode=0644

- name: create service
  copy: src=transparent_hugepages dest=/etc/init.d/transparent_hugepages mode=0755
  notify:
    - restart-transparent-hugepages

- name: service enable and start
  service: name=transparent_hugepages state=started enabled=yes
