#!/bin/sh
### BEGIN INIT INFO
# Provides:          disable-transparent-hugepages
# Required-Start:    $local_fs
# Required-Stop:
# X-Start-Before:    mongod mongodb-mms-automation-agent
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Disable Linux transparent huge pages
# Description:       Disable Linux transparent huge pages, to improve
#                    database performance.
### END INIT INFO

# copied from:
# https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/#transparent-huge-pages-thp-settings

SYSCONFIG="/etc/sysconfig/transparent_hugepages"
if [ -f "$SYSCONFIG" ]; then
  . "$SYSCONFIG"
fi

RETVAL=0
case $1 in
  start)
    echo "${MODE}" > /sys/kernel/mm/transparent_hugepage/enabled
    echo "${MODE}" > /sys/kernel/mm/transparent_hugepage/defrag
    ;;
  status)
    # check if both values are set, else return false
    for setting in enabled defrag; do
      grep "\[${MODE}\]" /sys/kernel/mm/transparent_hugepage/${setting} || RETVAL=1; break
    done
    ;;
esac

RETVAL=1
